version: "3.8"
services:
    mongodb:
        image: mongo
        container_name: mongodb
        ports:
            - 27017:27017
        volumes:
            - data:/data
        environment:
            MONGO_INITDB_ROOT_USERNAME: rootuser
            MONGO_INITDB_ROOT_PASSWORD: rootpass
        networks:
            - mongodb_network
    mongo-express:
        image: mongo-express
        container_name: mongo-express
        restart: unless-stopped
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: rootuser
            ME_CONFIG_MONGODB_ADMINPASSWORD: rootpass
            ME_CONFIG_MONGODB_SERVER: mongodb
            ME_CONFIG_MONGODB_PORT: 27017
            ME_CONFIG_BASICAUTH_USERNAME: admin
            ME_CONFIG_BASICAUTH_PASSWORD: test
        networks:
            - mongodb_network
        depends_on:
            -   mongodb
volumes:
    data: {}

networks:
    mongodb_network:
        driver: bridge