spring:
  data:
    mongodb:
      authentication-database: admin
      username: rootuser
      password: rootpass
      database: mongodemo
      host: localhost
      port: 27017
      uri: mongodb://rootuser:rootpass@localhost:27017/mongodemo?authSource=admin
      auto-index-creation: true